In [1]:
import pandas

In [2]:
%%time
df = pandas.read_csv('r1/output1.sam', skiprows=188758, sep='\t', header=None, on_bad_lines="skip", dtype={12: str})
df.head()
print(df.shape)

# reads that align
aligned = df[df[4] == 255]
print(aligned.shape)

# unique alignments
unique1 = aligned[aligned[11] == 'NH:i:1']
print(unique1.shape)

df.head()

(40747696, 13)
(20122287, 13)
(1566599, 13)
CPU times: user 1min 57s, sys: 29.1 s, total: 2min 26s
Wall time: 2min 41s

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,A00953:91:HC2F7DSXY:3:1101:17598:1000,16,ENST00000277480.7,508,255,101M,*,0,0,AGTTTCTCAAAACAGGGAGTACTTCAAGATCACCCTCTACGGGAGA...,FFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF...,NH:i:1,ZW:f:1
1,A00953:91:HC2F7DSXY:3:1101:18665:1000,0,ENST00000613167.4,5046,255,101M,*,0,0,GTTGCCCAGGCTGGAGTGCAGTGGCTATTCACAGGCGCGATCCCAC...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,NH:i:1,ZW:f:1
2,A00953:91:HC2F7DSXY:3:1101:21016:1000,4,*,0,0,*,*,0,0,GTGCTAGTGCTCTCATGGCGTCTAGTTGTCACAACTACCCTGTGGA...,"FFF::FF,:F,FF:FF,:FF:F:FFFFF,FFFFFFFFFFF:F,F:F...",NaN,NaN
3,A00953:91:HC2F7DSXY:3:1101:21576:1000,0,ENST00000493837.6,688,255,101M,*,0,0,CTTCTTCTCCCCACTCTCCCAGGCAACCTGGCTGCTCCTGGCCCTT...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F...,NH:i:1,ZW:f:1
4,A00953:91:HC2F7DSXY:3:1101:22480:1000,4,*,0,0,*,*,0,0,AGGCTTAATGGCACACACCTGTAATCCCAGCAACTCAGGAGGTTGT...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,NaN,NaN

In [3]:
%%time
df = pandas.read_csv('r2/output2.sam', skiprows=188766, sep='\t', header=None, on_bad_lines="skip", dtype={12: str})
df.head()
print(df.shape)

# reads that align
aligned2 = df[df[4] == 255]
print(aligned2.shape)

# # unique alignments
# unique2 = aligned2[aligned[11] == 'NH:i:1']
# print(unique1.shape)

df.head()

(37516341, 13)
(16601218, 13)
CPU times: user 1min 57s, sys: 29.9 s, total: 2min 27s
Wall time: 2min 40s

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,A00953:91:HC2F7DSXY:3:1101:29441:1000,0,ENST00000335295.4,14,255,101M,*,0,0,ACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCAC...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,NH:i:4,ZW:f:0.995872
1,A00953:91:HC2F7DSXY:3:1101:29441:1000,256,ENST00000647020.1,140,255,101M,*,0,0,ACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCAC...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,NH:i:4,ZW:f:0.00384495
2,A00953:91:HC2F7DSXY:3:1101:29441:1000,256,ENST00000633227.1,14,255,101M,*,0,0,ACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCAC...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,NH:i:4,ZW:f:0.000279482
3,A00953:91:HC2F7DSXY:3:1101:29441:1000,256,ENST00000485743.1,15,255,101M,*,0,0,ACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCAC...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,NH:i:4,ZW:f:3.88331e-06
4,A00953:91:HC2F7DSXY:3:1101:29948:1000,4,*,0,0,*,*,0,0,TTCTCTTCTGCAATTACAGATTGCTTTGGTTATTTGTTGTTTTAAG...,FFFFFFFFFFFF:FFFFFFFFFFFFF:FFFFFFFFF:FFFFFFFFF...,NaN,NaN

In [ ]:
%%time

# total is 1,566,599

# necio5
# 100 trials takes circa 3 min: all successes (72)
# 1,000 trials take circa 43 min: 670 successes; 22 failures; 3%
# 10,000 trials takes circa 5 h: 6818 successes; 193 failures; 3%
 
# mimir
# 1,000 trials takes circa 32 min: 670 successes; 22 failures; 3%
# 100,000 trials takes circa 37 h, 21421 successes; 632 failures; 3%

successes = 0; failures = 0; trials = 100000

for index, row in unique1.head(trials).iterrows():
    name1 = row[0]
    transcript1 = row[2]
    hit = sum(aligned2[0] == name1)
    if hit == 1:
        transcript2 = aligned2[aligned2[0] == name1][2].to_list()[0]
        if transcript1 == transcript2:
            #print('SUCCESS', name1, transcript1)
            successes = successes + 1
        else:
            print('FAILURE', name1, transcript1, transcript2)
            print(aligned2[aligned2[0] == name1])
            failures = failures + 1

print(trials, successes, failures)