In [1]:
import pandas

In [2]:
# get the idr peaks. 
# get the two values per replicate, calculate the median
# get the color if it has passed the thresholds in one, two or three. gold, orange or red
# make the same figure but with viridis on the length to see if the patterns are good of TF binding site

In [3]:
wd = '/Users/adrian/research/bmcbf/004_keilir/results/1023_idr_results/MITF_A/'
consensus_file = 'MITF_A.IDR_consensus.bed'

In [17]:
con = pandas.read_csv(wd+consensus_file, sep='\t', header=None)
con.columns = ["chr", "start", "end"]
print(con.shape)

con = con.iloc[:100, :]

con['peak_id'] = con["chr"].astype(str) + ":" + con["start"].astype(str) + "-" + con["end"].astype(str)
con = con.set_index("peak_id")

con

(41664, 3)

                       chr    start      end
peak_id
chr1:910547-911772    chr1   910547   911772
chr1:912004-912799    chr1   912004   912799
chr1:921531-924309    chr1   921531   924309
chr1:930276-932047    chr1   930276   932047
chr1:936850-940044    chr1   936850   940044
...                    ...      ...      ...
chr1:2104508-2105429  chr1  2104508  2105429
chr1:2106769-2107536  chr1  2106769  2107536
chr1:2108029-2108859  chr1  2108029  2108859
chr1:2130619-2131272  chr1  2130619  2131272
chr1:2135476-2136663  chr1  2135476  2136663

[100 rows x 3 columns]

In [16]:
#  signal, P value, Q value and distance to summit. Signal is the same as fold enrichment in xls. not log2 FC, but just FC
df = pandas.read_csv(wd+'rep1.idr.sorted.narrowPeak', sep='\t', header=None)
df = df.rename(columns={0: 'chr', 1: 'start', 2:'end', 6:'FE', 8:'qvalue'})
df['peak_id'] = df["chr"].astype(str) + ":" + df["start"].astype(str) + "-" + df["end"].astype(str)
df = df.set_index("peak_id")

df

,chr,start,end,3,4,5,FE,7,qvalue,9
peak_id,,,,,,,,,,
chr7:77122267-77122531,chr7,77122267,77122531,MITF_A_FLAG1_vs_IgG1_peak_160360,538,.,17.53270,61.52170,53.88800,201
chr19:15418941-15419326,chr19,15418941,15419326,MITF_A_FLAG1_vs_IgG1_peak_87574b,493,.,14.61840,56.71280,49.37100,205
chr11:119121249-119121759,chr11,119121249,119121759,MITF_A_FLAG1_vs_IgG1_peak_37650a,483,.,13.56700,55.63850,48.38300,149
chr4:3955378-3956114,chr4,3955378,3956114,MITF_A_FLAG1_vs_IgG1_peak_138909d,312,.,12.98580,37.43090,31.28670,524
chr17:8155753-8157076,chr17,8155753,8157076,MITF_A_FLAG1_vs_IgG1_peak_70746f,345,.,12.07700,40.97200,34.56300,892
...,...,...,...,...,...,...,...,...,...,...
chrM:2512-2593,chrM,2512,2593,MITF_A_FLAG1_vs_IgG1_peak_178964,364,.,1.29169,42.92940,36.41380,37
chrM:9047-9349,chrM,9047,9349,MITF_A_FLAG1_vs_IgG1_peak_178965a,155,.,1.21029,19.99500,15.55180,19
chrM:9047-9349,chrM,9047,9349,MITF_A_FLAG1_vs_IgG1_peak_178965b,129,.,1.19144,16.97780,12.92340,118
chrM:16424-16515,chrM,16424,16515,MITF_A_FLAG1_vs_IgG1_peak_178966,81,.,1.12400,11.37730,8.10309,32
chrM:9047-9349,chrM,9047,9349,MITF_A_FLAG1_vs_IgG1_peak_178965c,21,.,1.07869,4.15183,2.15013,202

In [18]:
subset = df.loc[df.index.intersection(con.index)]
subset

Empty DataFrame
Columns: [chr, start, end, 3, 4, 5, FE, 7, qvalue, 9]
Index: []

In [7]:
subset

Empty DataFrame
Columns: [chr, ini, end, 3, 4, 5, 6, 7, 8, 9]
Index: []

In [8]:
df

,chr,ini,end,3,4,5,6,7,8,9
0,chr7,77122267,77122531,MITF_A_FLAG1_vs_IgG1_peak_160360,538,.,17.53270,61.52170,53.88800,201
1,chr19,15418941,15419326,MITF_A_FLAG1_vs_IgG1_peak_87574b,493,.,14.61840,56.71280,49.37100,205
2,chr11,119121249,119121759,MITF_A_FLAG1_vs_IgG1_peak_37650a,483,.,13.56700,55.63850,48.38300,149
3,chr4,3955378,3956114,MITF_A_FLAG1_vs_IgG1_peak_138909d,312,.,12.98580,37.43090,31.28670,524
4,chr17,8155753,8157076,MITF_A_FLAG1_vs_IgG1_peak_70746f,345,.,12.07700,40.97200,34.56300,892
...,...,...,...,...,...,...,...,...,...,...
259878,chrM,2512,2593,MITF_A_FLAG1_vs_IgG1_peak_178964,364,.,1.29169,42.92940,36.41380,37
259879,chrM,9047,9349,MITF_A_FLAG1_vs_IgG1_peak_178965a,155,.,1.21029,19.99500,15.55180,19
259880,chrM,9047,9349,MITF_A_FLAG1_vs_IgG1_peak_178965b,129,.,1.19144,16.97780,12.92340,118
259881,chrM,16424,16515,MITF_A_FLAG1_vs_IgG1_peak_178966,81,.,1.12400,11.37730,8.10309,32
259882,chrM,9047,9349,MITF_A_FLAG1_vs_IgG1_peak_178965c,21,.,1.07869,4.15183,2.15013,202