In [13]:
import pandas, os

In [14]:
input_folder = '/Users/adrian/research/019.fossvogur/001_profiles/'

# a cases
a_cases = ['SkMel28-MITFKO_ev_skmel28_rep1', 'SkMel28-MITFKO_ev_skmel28_rep2', 'SkMel28-MITFKO_ev_skmel28_rep3', 'SkMel28-MITFKO_ev_skmel28_rep4', 
          'SkMel28-MITFKO_mitf_x6_rep1', 'SkMel28-MITFKO_mitf_x6_rep3', 'SkMel28-MITFKO_mitf_x6_rep4']

In [15]:
samples = os.listdir(input_folder)
samples.remove('messages')
samples.sort()
print(len(samples), samples) # should be 30 in this case

30 ['501-KO13_VHN-10_processed', '501-KO13_VHN-2_processed', '501-KO13_VHN-6_processed', 'C1-RD-16_processed', 'C1_RD-10_processed', 'C1_RD-4_processed', 'C3_RD-13_processed', 'C3_RD-1_processed', 'C3_RD-7_processed', 'KO13_VHN-11_processed', 'KO13_VHN-3_processed', 'KO13_VHN-7_processed', 'KO17_VHN-12_processed', 'KO17_VHN-4_processed', 'KO17_VHN-8_processed', 'KO24_VHN-1_processed', 'KO24_VHN-9_processed', 'SkMel28-MITFKO_ev_skmel28_rep1_processed', 'SkMel28-MITFKO_ev_skmel28_rep2_processed', 'SkMel28-MITFKO_ev_skmel28_rep3_processed', 'SkMel28-MITFKO_ev_skmel28_rep4_processed', 'SkMel28-MITFKO_mitf_x6_rep1_processed', 'SkMel28-MITFKO_mitf_x6_rep3_processed', 'SkMel28-MITFKO_mitf_x6_rep4_processed', 'siCTRL_1_processed', 'siCTRL_2_processed', 'siCTRL_3_processed', 'siMITF_1_processed', 'siMITF_2_processed', 'siMITF_3_processed']

In [30]:
expression = pandas.DataFrame()

for sample in samples[:1]:
    print('working with sample {}'.format(sample))

    label = sample.replace('_processed', '')
    if label in a_cases:
        target_file = input_folder + sample + '/kallisto_output_a' + '/abundance.tsv'
    else:
        target_file = input_folder + sample + '/kallisto_output_c' + '/abundance.tsv'
    print('\t {}'.format(target_file))

    df = pandas.read_csv(target_file, sep='\t', index_col=0)

    expression.join(df['tpm'], how='left')

df

working with sample 501-KO13_VHN-10_processed
	 /Users/adrian/research/019.fossvogur/001_profiles/501-KO13_VHN-10_processed/kallisto_output_c/abundance.tsv

                   length  eff_length  est_counts       tpm
target_id
ENST00000308647.8    2114    1836.000    6930.260  44.04770
ENST00000378736.3     414     176.294     829.955  54.93670
ENST00000472194.6    4314    4036.000    2112.580   6.10813
ENST00000474481.1    3367    3089.000     942.779   3.56154
ENST00000485748.5    3233    2955.000    1204.270   4.75567
...                   ...         ...         ...       ...
ENST00000619729.1     294      96.066       0.000   0.00000
ENST00000612640.4    2116    1838.000    2246.420  14.26240
ENST00000614336.4    3728    3450.000    1956.210   6.61671
ENST00000601199.2     510     252.334       0.000   0.00000
ENST00000612315.1     831     554.000       0.000   0.00000

[227665 rows x 4 columns]

In [31]:
expression

Empty DataFrame
Columns: []
Index: []